<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Se han actualizado las asignaciones',
    'Auth item with such name already exists' => 'El nombre para el Registro de Autenticación ya existe',
    'Class "{0}" does not exist' => 'La clase "{0}" no existe',
    'Classname of the rule associated with this item' => 'Nombre de clase de la regla asociada con este elemento',
    'Create' => 'Crear',
    'Create new permission' => 'Crear nuevo permiso',
    'Create new role' => 'Crear un nuevo rol',
    'Description' => 'Descripción',
    'Invalid value' => 'Valor no válido',
    'Item has been created' => 'El registro ha sido creado',
    'Item has been updated' => 'El registro ha sido actualizado',
    'Name' => 'Nombre',
    'New permission' => 'Nuevo Permiso',
    'New role' => 'Nuevo Rol',
    'New user' => 'Nuevo Usuario',
    'Permissions' => 'Permisos',
    'Roles' => 'Roles',
    'Rule class can not be instantiated' => 'La clase de regla no se puede instanciar',
    'Rule class must extend "yii\rbac\Rule"' => 'Las reglas de la clase deben heredarse "yii\rbac\Rule"',
    'Rule name' => 'Nombre de Regla',
    'Save' => 'Guardar',
    'The item description (Optional).' => 'La descripción del registro (opcional).',
    'The name of the item.' => 'El nombre del elemento.',
    'There is neither role nor permission with name "{0}"' => 'No hay rol ni permiso con nombre "{0}"',
    'Update assignments' => 'Actualizar asignación',
    'Update permission' => 'Actualizar Permiso',
    'Update role' => 'Actualizar Rol',
    'Users' => 'Usuarios',
];
